### ISSUE TITLE
data放数据了， 但是没出来树

### ISSUE THREAD

**Issue by KsssAlleria** [ayiaq1/el-tree-select#1]
有个这样的警告
vue.esm.js?efeb:591 [Vue warn]: Error in event handler for "updatePopper": "TypeError: o is not a constructor"

found in

**Comment by ayiaq1** [comment]
是否是最新的版本？另外贴一下代码呢

**Comment by zongcong** [comment]
怎么双向绑定让树节点被勾中？

**Comment by ayiaq1** [comment]
@zongcong 贴一下代码

**Comment by ayiaq1** [comment]
没有回复，关闭此问题
