### ISSUE TITLE
多选清空值报错

### ISSUE THREAD

**Issue by pengyinghao** [ayiaq1/el-tree-select#14]
1、It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key.
 2、"TypeError: Cannot read property 'key' of undefined"
给出的demo全部选中后 清空某一个报错

**Comment by ayiaq1** [comment]
贴一下代码呢

**Comment by ayiaq1** [comment]
demo的数据重复导致的，已提交git，但不用重新打包
