### ISSUE TITLE
多选清除单个Tag, Tree勾选状态未同步

### ISSUE THREAD

**Issue by liaobinbin** [ayiaq1/el-tree-select#16]
版本3.0.10
在多选状态下， 点击单个tag后的x，下拉的tree未同步。

能否关闭调多选状态下的tag的x按钮，仅保留下拉勾选的操作？

谢谢。

**Comment by ayiaq1** [comment]
贴一下代码呢，点击tag同步树的勾选状态测试是通过的

**Comment by liaobinbin** [comment]
我测试到的结果是
check-strictly 为true的话，tag和tree是同步的。
但是check-strictly是false的话，点击tag，无法与tree同步。 只能点击tree，然后tag可以同步

**Comment by liaobinbin** [comment]
check-strictly为true时，
一级tag 可以同步tree,
二级tag 没法同步tree

check-strictly为false时，
tag一个都没法同步到tree

但是tree同步到tag都是没问题的

但是好像是我的锅啊，我下了你的demo 跑起来没有问题啊。 我再研究一下

**Comment by liaobinbin** [comment]
#17 已修复

**Comment by ayiaq1** [comment]
确定是each默认传子节点名称：children 导致的，3Q！
