### ISSUE TITLE
单选模式下会报“Cannot set property 'isCurrent' of null”，多选下没问题。

### ISSUE THREAD

**Issue by samyhd** [ayiaq1/el-tree-select#26]
在单选模式下报
[Vue warn]: Error in callback for watcher "ids": "TypeError: Cannot set property 'isCurrent' of null"
如下图：

![image](https://user-images.githubusercontent.com/10351607/60771129-c56ab280-a115-11e9-9063-75527b260cc8.png)

同样的配置，仅仅把multiple改成true，就没此错误提示。代码按示例编写。

2019-07-07 在npm上获取的最新版本。

麻烦看下，谢谢分享。

**Comment by ayiaq1** [comment]
单选模式下  id应该为 id:''  字符串 多选才是  id:[] 数组
