### ISSUE TITLE
有时会报 e.className.indexOf is not a function

### ISSUE THREAD

**Issue by samyhd** [ayiaq1/el-tree-select#28]
如下图：
![image](https://user-images.githubusercontent.com/10351607/60866373-c78a5980-a25a-11e9-8bce-ab12c697b2b2.png)

我看代码处如下：
![image](https://user-images.githubusercontent.com/10351607/60866496-1637f380-a25b-11e9-96c6-de671da25692.png)

望完善，谢谢分享。

**Comment by ayiaq1** [comment]
贴一下你的完整代码呢 你修改了class名称?

**Comment by samyhd** [comment]
我没有改，很简单的测试应用，就下面两块地方涉及到

![image](https://user-images.githubusercontent.com/10351607/60877688-e3005f00-a270-11e9-9385-eb870dec4201.png)

![image](https://user-images.githubusercontent.com/10351607/60877719-f57a9880-a270-11e9-996e-ee8c3682514c.png)

偶尔发生的，我也比较难重现

**Comment by ayiaq1** [comment]
这个组件在至少20个项目里面使用，没有出现过这个问题，最好你给在线地址或者追踪报错原因

**Comment by samyhd** [comment]
你那边是否可以加上保护，在className明确是一个字符时才调用 indexOf ？

**Comment by ayiaq1** [comment]
既然有报错必定有原因，否则功能会有问题

**Comment by ayiaq1** [comment]
追踪没有结果，close

**Comment by xdxiaodong** [comment]
这个问题确实存在，我也遇到了相同的问题，<el-popover>里的<svg>出发click时间，就会报错

**Comment by xdxiaodong** [comment]
这个问题确实存在，我也遇到了相同的问题，`<el-popover>`里的`<svg>`触发click事件或者直接点击<svg>，就会报错

**Comment by ayiaq1** [comment]
https://ayiaq1.github.io/el-tree-select/storybook-static/?path=/story/%E6%B8%B2%E6%9F%93--%E9%80%9A%E8%BF%87props%E4%BC%A0%E5%8F%82%E6%95%B0  在线测试下 点击箭头和图标 没有触发该问题，贴一下代码，以及使用得版本号

**Comment by xdxiaodong** [comment]
版本3.1.4，这个问题是我在做图标选择组件时发现的，涉及到的代码比较多，在出现问题的时候我把`el-tree-select`屏蔽掉问题即消失，这个问题应该是其他组件触发了`el-tree-select`的`_popoverHideFun`而`_popoverHideFun`内判断不严谨导致的报错，`<el-tree-select />`任何参数不设置也会100%报错

**Comment by ayiaq1** [comment]
晚一点加一个是否存在的判断，但是因为没有具体得代码无法直接追踪。

**Comment by xdxiaodong** [comment]
![Snipaste_2019-09-27_17-35-00](https://user-images.githubusercontent.com/7643447/65759315-3c2fae80-e14d-11e9-92c2-36201bd891db.png)

**Comment by ayiaq1** [comment]
3.1.5增加了兼容性判断，最好提供一下模板代码便于调试

**Comment by xdxiaodong** [comment]
我刚才升级到3.1.5问题还是存在，我写个测试demo

**Comment by xdxiaodong** [comment]
测试demo写好了，地址：https://github.com/xdxiaodong/el-tree-select-demo-bug.git

**Comment by ayiaq1** [comment]
非常感谢，3.1.6 已解决

**Comment by xdxiaodong** [comment]
3.1.6 chrome控制台报错的问题已经解决，firefox和edge报错的问题依然存在，他俩的问题跟chrome的报错问题差不多，用我之前发的demo可以测试。报错的触发方法跟chrome一样。  
edge   
`0: Unable to get property 'some' of undefined or null reference
el-tree-select.umd.min.js (1,1)`
firefox   
```
TypeError: t.path is undefined
_popoverHideFun el-tree-select.umd.min.js:1
_popoverHideFun self-hosted:1003
````

**Comment by ayiaq1** [comment]
3.1.7 
处理MouseEvent多浏览器兼容性判断
