### ISSUE TITLE
单选模块报：Error in callback for watcher "ids": "TypeError: Cannot set property 'isCurrent' of null"

### ISSUE THREAD

**Issue by samyhd** [ayiaq1/el-tree-select#29]
按DEMO的代码，在单选模块时以下两种设置均会报
Error in callback for watcher "ids": "TypeError: Cannot set property 'isCurrent' of null"

![image](https://user-images.githubusercontent.com/10351607/61953158-436cfb80-afe8-11e9-88d1-d5e45401c684.png)

1）把DEMO里的 values: ['11111'] 改成 values: null，会报。有时初始化时valuas可能是空值，请考虑兼容这种情况。

2）把DEMO里的 values: ['11111'] 改成 values: ''，且把data 改成 空数组，即 data: []，mounted中也不提供数据，也会报上述错误。

请看能否兼容处理，谢谢分享。

**Comment by ayiaq1** [comment]
空数据默认应该为 数组、字符串、数字 不对错误数据做兼容

**Comment by samyhd** [comment]
》》》空数据默认应该为 数组、字符串、数字 不对错误数据做兼容
这个只是针对第一点回复了

至于我提的第二点“2）把DEMO里的 values: ['11111'] 改成 values: ''，且把data 改成 空数组，即 data: []，mounted中也不提供数据，也会报上述错误。”

这个并不是空数据，而是data为正确的数据，只不过是0项数据，数组为0大小而已，现在也是出错的，麻烦再看下。

**Comment by ayiaq1** [comment]
你的另外一个issues我回复了 ，内置 selectParams.multiple。这样就不会存在类型为：数组，但是你设置了selectParams.multiple,=false 导致判断为字符串的问题 。
[在线测试](https://ayiaq1.github.io/el-tree-select/storybook-static/?path=/story/*) 我重新打包提交了
