### ISSUE TITLE
value类型目前只能为String,Array，是否可以加上 Number

### ISSUE THREAD

**Issue by samyhd** [ayiaq1/el-tree-select#30]
后台有时返回的id数值确实是number类型，控制台的提示蛮烦的

Invalid prop: type check failed for prop "value". Expected String, Array, got Number with value 7.

能否支持上Number，这样兼容性更高，也不用调整业务数据结构

后台是水那也没办法 ：（

望能采纳，谢谢分享。

**Comment by ayiaq1** [comment]
3.1.4 去掉selectParams.multiple参数，改为内置，由v-model判断类型,v-model增加Number类型
