### ISSUE TITLE
报Cannot read property 'updatePopper' of undefined

### ISSUE THREAD

**Issue by samyhd** [ayiaq1/el-tree-select#31]
提示：
Uncaught TypeError: Cannot read property 'updatePopper' of undefined
    at el-tree-select.umd.min.js:1

出现上面的提示，能否看下是那里的问题。

我看到源码有一句： this.$refs.popover.updatePopper();，是否这里this.$refs.popover未可用？

谢谢分享

**Comment by ayiaq1** [comment]
提一下代码？

**Comment by ayiaq1** [comment]
没有回复，测试没问题，关闭
