### ISSUE TITLE
设置多选失效

### ISSUE THREAD

**Issue by leishihong** [ayiaq1/el-tree-select#35]

**Comment by ayiaq1** [comment]
贴代码

**Comment by leishihong** [comment]
版本没有更新导致的，刚看一一下api文档，大佬好牛班

**Comment by carveybunt** [comment]
@leishihong  大佬，您的多选是怎么设置的？我clone最新的项目了，还是设置无效。

**Comment by leishihong** [comment]
@carveybunt 3.1.4  去掉selectParams.multiple参数，改为内置，由v-model判断类型,v-model增加Number类型
![image](https://user-images.githubusercontent.com/26375364/73624814-33ac2f00-467d-11ea-806e-6d2b0be1ede0.png)

**Comment by carveybunt** [comment]
@leishihong 多谢，已解决
