### ISSUE TITLE
treeParams中的data无法绑定vuex变量

### ISSUE THREAD

**Issue by bydraw** [ayiaq1/el-tree-select#36]
### 环境：
"el-tree-select": "^3.1.4",
"element-ui": "^2.12.0",
"vue": "^2.5.2",
"vuex": "^3.1.1"
### 问题（简写）
**代码**
**-template**
`<el-tree-select :treeParams="{data:dataList}"></el-tree-select>`

**-script**
`computed:{...mapState('dataList')}`
**结果**
Vue Dev tools中可以明确观察到
ElTreeSelect已得到正确的treeParams[data]数组prop
但实际内部的Eltree中,data为空

**Comment by ayiaq1** [comment]
考虑性能，数据没有做watch监听需要手动触发this.$refs.treeSelect.treeDataUpdateFun(response.data);

**Comment by ayiaq1** [comment]
初始数据可以绑定 treeParams.data 数据变更走方法，否则watch数据会很耗性能

**Comment by bydraw** [comment]
**感谢回复，手动更新数据确实解决了问题**。
另外，如果应用场景类似于“**组件绑定的data为action中返回的state数据**”，似乎可以给组件加上**v-if="data.length > 0"**，自动响应以重绘节点。

**Comment by ayiaq1** [comment]
树节点多消耗性能，建议还是走触发，不做dom的销毁和重绘，如果是在大数据量下很容易卡

**Comment by bydraw** [comment]
好的，感谢。
