### ISSUE TITLE
element tree方法支持

### ISSUE THREAD

**Issue by nonokang** [ayiaq1/el-tree-select#37]
1、为何不支持element tree的方法，如：getNode/getCurrentNode/setChecked等
2、通过v-model绑定的初始化数据，每个tag都无法删除

**Comment by ayiaq1** [comment]
this.$refs.treeSelect.$refs.tree.xxxx  这样支持element-ui的所有树方法

tag无法删除的问题，贴一下代码版本号？

**Comment by ayiaq1** [comment]
没有回复，如果有结果会根据情况reopen
