### ISSUE TITLE
遇到个问题，value值存在的时候有时候文本框显示的数据依然为空

### ISSUE THREAD

**Issue by AK47-dadada** [ayiaq1/el-tree-select#38]
`<el-select-tree
              style="width: 100%"
              check-strictly
              node-key="value"
              placeholder="请选择所属队伍"
              :data="orgTree"
              @change="orgTreeChange"
              v-model="form.orgId"
            ></el-select-tree>`
也就是数据回显的时候 我这个orgId是存在的，但是输入框为空
![image](https://user-images.githubusercontent.com/30396595/70720350-9c86c300-1d2e-11ea-9216-e29684c115bb.png)

**Comment by ayiaq1** [comment]
发一下 orgTree  以及 props  呢 应该是对应的id 没有匹配到

**Comment by AK47-dadada** [comment]
昨晚熬夜检查了一下，发现这个插件在数据回显的时候，如果数据加载慢了，不会自动响应的，id肯定是有的，是这个问题

**Comment by ayiaq1** [comment]
在数据变更时,如果你触发了(treeDataUpdateFun) 该方法 会延迟做回显判断
this.$refs.selectTree.treeDataUpdateFun(treeData);
```
treeDataUpdateFun(data) {
            this.data = data;
            // 数据更新完成之后，判断是否回显内容
            if (data.length > 0) {
                setTimeout(() => {
                    this._setSelectNodeFun(this.ids);
                }, 300);
            }
        }
```

**Comment by AK47-dadada** [comment]
我最终解决方案是获取数据之后才调用查询 不然这个有点小坑
可以吧这个做成响应式的不，不然来回渲染有点心塞啊

**Comment by ayiaq1** [comment]
这本来就是一个双向的数据 方便贴一下代码么

**Comment by AK47-dadada** [comment]
晚点啦 大兄弟 这会儿在改别的项目的代码 QAQ

**Comment by ayiaq1** [comment]
没有后续回复,后续确认为bug,会reopen该问题
