### ISSUE TITLE
大佬，无法开启多选，以及搜索

### ISSUE THREAD

**Issue by carveybunt** [ayiaq1/el-tree-select#41]
可有使用说明文档呀？您的文档里面没看到相关的说明，求指点。

**Comment by ayiaq1** [comment]
在线测试可以看到相关配置使用方式

**Comment by carveybunt** [comment]
> 在线测试可以看到相关配置使用方式

大佬，您好，在线测试，不知道怎么的打开好慢，不知道还有其他在线测试的途径吗？

**Comment by carveybunt** [comment]
@ayiaq1 大佬，新年快乐。
没看到想管的设置以及方法的操作呀.求指点下。
![image](https://user-images.githubusercontent.com/37894474/73443112-0b78b380-4391-11ea-931c-60ae8cc8a45e.png)
![image](https://user-images.githubusercontent.com/37894474/73443147-1cc1c000-4391-11ea-829b-1e6dd28d0f10.png)

**Comment by ayiaq1** [comment]
https://github.com/ayiaq1/el-tree-select/blob/master/src/App.vue

这是以前的测试文件，可以参考下

**Comment by carveybunt** [comment]
> https://github.com/ayiaq1/el-tree-select/blob/master/src/App.vue
> 
> 这是以前的测试文件，可以参考下

@ayiaq1  您的整个项目的都clone了，就是在本地运行无法实现多选以及过滤的。

![image](https://user-images.githubusercontent.com/37894474/73445795-6e207e00-4396-11ea-853c-0f9e6e647fee.png)

**Comment by ayiaq1** [comment]
{
  "treeParams":｛
filterable:true
},
  "multiple": true
}

**Comment by carveybunt** [comment]
> {
> "treeParams":｛
> filterable:true
> },
> "multiple": true
> }

@ayiaq1 大佬，组件里面不设置什么吗？
![image](https://user-images.githubusercontent.com/37894474/73447270-4ed72000-4399-11ea-92a2-ad9c7cf9edd1.png)

**Comment by ayiaq1** [comment]
你贴下代码吧，手机上的

**Comment by carveybunt** [comment]
@ayiaq1 那就麻烦大佬了。看了很久的文档，也 试了很久没弄好多选，以及本地过滤。
`<ElTreeSelect v-model="values" :styles="styles" :selectParams="selectParams" :treeParams="treeParams" ref="treeSelect"></ElTreeSelect>`

            values: '',
            selectParams: {
                clearable: true,
                placeholder: '请输入内容'
            },
            treeParams: {
                clickParent: true,
                filterable: true,
                'check-strictly': true,
                'default-expand-all': true,
                'expand-on-click-node': false,
                'render-content': this._renderFun,
                data: [
                    {
                        testId: 1,
                        name: '节点1',
                        disabled: true,
                        child: [
                            {
                                testId: 111111,
                                name: '子节点'
                            }
                        ]
                    },
                    {
                        testId: 3,
                        name: '节点3'
                    }
                ],
                props: {
                    children: 'child',
                    label: 'name',
                    disabled: 'disabled',
                    value: 'testId'
                }
            },
          "multiple": true

**Comment by ayiaq1** [comment]
selectParams: {
            clearable: true,
multiple:true,
            placeholder: '请输入内容'
        }
放文本框的附加参数内

**Comment by carveybunt** [comment]
@ayiaq1 大佬，调整了设置，还是无法实现多选呢。

      selectParams: {
            clearable: true,
            multiple:true,
            placeholder: '请输入内容'
        },

![image](https://user-images.githubusercontent.com/37894474/73511371-65748a00-4420-11ea-9c61-24ffdbf43884.png)

**Comment by ayiaq1** [comment]
版本号多少？
用在线工具引入JS，贴上你的代码看看呢
https://unpkg.com/el-tree-select@3.1.7/dist/el-tree-select.umd.min.js

**Comment by carveybunt** [comment]
clone您的项目的master，我前端基础差，我学的是后端。
![image](https://user-images.githubusercontent.com/37894474/73511904-70c8b500-4422-11ea-9fc3-b1d9b48a4f6a.png)

**Comment by ayiaq1** [comment]
做了一个在线demo:
https://codepen.io/ayiaq1/pen/rNaEzdz?editors=1010

v-model的值 也需要为一个数组

**Comment by carveybunt** [comment]
多谢大佬的指点，我发现，不用设置multiple:true。
单选多选通过设置values就可以了。
拉取下来的项目，默认设置values: '',是单选；改为values: [],则为多选。

还请大佬指点下如何实现过滤。

**Comment by ayiaq1** [comment]
<ElTreeSelect v-model="values" :styles="styles" :selectParams="selectParams" :treeParams="treeParams" ref="treeSelect" @searchFun="_searchFun"></ElTreeSelect>



_searchFun(value) {
            console.log(value, '<--_searchFun');
            // 自行判断 是走后台查询，还是前端过滤
            // this.$refs.treeSelect.$refs.tree.filter(value);
            this.$refs.treeSelect.filterFun(value);
            // 后台查询
            // this.$refs.treeSelect.treeDataUpdateFun(treeData);
        },

**Comment by carveybunt** [comment]
万分感谢大佬的耐心指点，全部OK。
