### ISSUE TITLE
同时引入2个该组件，其中一个无数据，希望大佬指点一二

### ISSUE THREAD

**Issue by carveybunt** [ayiaq1/el-tree-select#42]
不得不说这个组件确实挺好用，感谢作者大佬。
在同一个页面中引用了2个该组件，其中一个无数据。
![image](https://user-images.githubusercontent.com/37894474/73517386-4bde3d00-4436-11ea-83da-bff0433f52f3.png)
![image](https://user-images.githubusercontent.com/37894474/73517400-54cf0e80-4436-11ea-9b1d-9ec65fad4fc5.png)

       <el-form-item label="权限" prop="parent_id">
        <ElTreeSelect
          ref="permissionTreeSelect"
          v-model="PermisSelectTreeClinkValues"
          :styles="TreeSelectWidth"
          :select-params="selectParams"
          :tree-params="SelectPermisTreeParams"
          @searchFun="_searchPermisFun"
          @node-click="_permisNodeClickFun"
        />
      </el-form-item>
      <el-form-item label="上级菜单" prop="parent_id">
        <ElTreeSelect
          ref="menuTreeSelect"
          v-model="MenuSelectTreeClinkValues"
          :styles="TreeSelectWidth"
          :select-params="selectParams"
          :tree-params="SelectMenuTreeParams"
          @searchFun="_searchMenuFun"
          @node-click="_menuNodeClickFun"
        />
      </el-form-item>

**Comment by ayiaq1** [comment]
使用this. refs. xx. tree updata Fun 方法设置

**Comment by carveybunt** [comment]
是这个方法吗？
    /**
       * @vuese
       * 树列表更新数据
       * @arg Array
       */
    treeDataUpdateFun(data) {
      this.data = data
      // 数据更新完成之后，判断是否回显内容
      if (data.length > 0) {
        setTimeout(() => {
          this._setSelectNodeFun(this.ids)
        }, 300)
      }
    },

我控制台打印无数据的组件的data都有数据，不知道怎么的就是不会显示。
用this.$refs.permissionTreeSelect.treeDataUpdateFun(this.SelectTreePer)，this.SelectTreePer是我存的data。但是报错
![image](https://user-images.githubusercontent.com/37894474/73522770-412aa480-4444-11ea-9ad6-ee0fb87b9d0c.png)

**Comment by ayiaq1** [comment]
nextTick之后才能拿到refs内容

**Comment by carveybunt** [comment]
多谢大佬，不过好像是我后端数据出了问题，现在OK了。
再次感谢大佬的指点。

如果，搜索能优化成，输入字符自动搜索就好了。

**Comment by ayiaq1** [comment]
el-tree有性能问题，节流搜索对大数据量情况同样不实用，新版本自写树有专利没有发出来

**Comment by carveybunt** [comment]
大佬，不好意思又要麻烦您了。
我做了数据的新增操作后，页面的树形数据里面有新增的内容。
select里面的数据 = 页面的树形数据
为什么在下拉选择器里面显示的内容不会刷新呀？
![image](https://user-images.githubusercontent.com/37894474/73592857-c2179800-4539-11ea-908e-501bc32eef26.png)

**Comment by ayiaq1** [comment]
树数据没有做watch. 考虑性能需要手动执行tree Updata Fun方法

**Comment by carveybunt** [comment]
大佬，我在您的组件里面没找到相关的tree Updata Fun方法，在element tree也没找到相关的更新数据的方法。原谅我的基础差，求指点下。

**Comment by carveybunt** [comment]
大佬，研究了2天还是没弄解决这个问题
用了您的treeDataUpdateFun
![image](https://user-images.githubusercontent.com/37894474/73806337-2e2d2100-4804-11ea-8de0-c30c51b9828f.png)
也是不行，我基础差，求指点下。

**Comment by ayiaq1** [comment]
贴一下你的代码，以及问题是什么

**Comment by carveybunt** [comment]
添加成功后，能从API获取待最新的数据，页面的树形结构也是最新的数据。但是在表单中的树形下拉选择器中没有新增的数据项。 如图 测试3
![image](https://user-images.githubusercontent.com/37894474/73806912-cbd52000-4805-11ea-9c9c-9eb1b1fdb457.png)


    createDepartData() { // 添加部门
      this.$refs['dataformdeparts'].validate((valid) => {
        if (valid) {
          addDepart(this.deparTemp).then(() => {
            this.dialogDepatFormVisible = false
            this.$notify({
              title: '系统提示',
              message: '部门添加成功',
              type: 'success',
              duration: 3000
            })
            this.getDeparttreeData() // 重新从API获取添加后的数据列表
            this.departTreeDataUpdateFun(this.departmentTreeData) // this.departmentTreeData 部门的树形数据
          })
        }
      })
    },
    getDeparttreeData() {
      getDepartsTree().then(response => {
        const data = response.data
        this.departmentTreeData = data
      })
    },
    departTreeDataUpdateFun(data) {
      this.$refs.departtreeselect.treeDataUpdateFun(data)
    },

**Comment by ayiaq1** [comment]
getDeparttreeData() {
  getDepartsTree().then(response => {
    const data = response.data
    this.departmentTreeData = data
this.$refs.departtreeselect.treeDataUpdateFun(data) // 应该写到数据返回之后
  })
},

**Comment by carveybunt** [comment]
多谢大佬，搞定了。
