### ISSUE TITLE
popoverClass 无法使用

### ISSUE THREAD

**Issue by zhaogituser** [ayiaq1/el-tree-select#43]
<div data-v-54ba83ba="" data-v-1b44a2b5="" class="el-select common_search_input el-select--small" styles="styles" popoverclass="small_popover" popper-class="popperClass" selectclass="small_select" placement="top"> 生成代码  该属性最终会被加载到select部分 参考官网el-selecet popoverClass会成功作用到popover上。

**Comment by zhaogituser** [comment]
`<div data-v-54ba83ba="" data-v-1b44a2b5="" class="el-select common_search_input el-select--small" styles="styles" popoverclass="small_popover" popper-class="popperClass" selectclass="small_select" placement="top">`

**Comment by ayiaq1** [comment]
在线测试OK:
https://ayiaq1.github.io/el-tree-select/storybook-static/?path=/story/%E6%B8%B2%E6%9F%93--%E9%80%9A%E8%BF%87props%E4%BC%A0%E5%8F%82%E6%95%B0
3.1.7本地跑了一下,没有问题.
但是做了一次最新版本打包发布.尝试更新.

**Comment by ayiaq1** [comment]
没有回复关闭.
