### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by cdfan** [ayiaq1/el-tree-select#45]
作者你好，首先非常感谢你能够分享这个组件。

在平常的使用中这个组件是没有什么问题的，但是也发现了一个问题：

- 那就是在搜索输入框中好像没有类似于clearable将文本清理的功能，如果能够加上那就更完美了，如果自己在本地改，每次重新安装依赖都要去改一下源码挺麻烦的

这是我一个小小的建议，还望采纳，谢谢

**Comment by barclaycc** [comment]
也是上来想交流这个问题，搜索框中的keywords值如果可控就好了
