### ISSUE TITLE
下拉出现选择列表出现2个滚动条

### ISSUE THREAD

**Issue by samyhd** [ayiaq1/el-tree-select#47]
把源码中的ElTreeSelect.vue、dom.js、utils.js下载到本地
在文件中引入使用

发觉在下拉列表会出现两个滚动条
1）如果鼠标在左边的滚动条内部时双指滚动，那动的是左边的滚动条
2）如果鼠标在左边的滚动条外部时双指滚动，那动的是右边的滚动条

请问是那里的问题，谢谢

![image](https://user-images.githubusercontent.com/10351607/79050176-e939c680-7c5a-11ea-85c1-0584ba8997f9.png)

**Comment by ayiaq1** [comment]
你本地样式有复写吧。我建立了一个全新工程，只有一个内置滚动条

**Comment by samyhd** [comment]
感谢，确实是我复写了一个样式，想让下拉项显示更多点

`.el-select-dropdown__wrap {
  max-height: 550px;
}`
