### ISSUE TITLE
树点击事件disabled值判定无效

### ISSUE THREAD

**Issue by qq1390229143** [ayiaq1/el-tree-select#52]
this.treeParams.props.disabled为空时,propsDisabled赋值是undefined,导致树点击事件判定有误
propsDisabled需要默认值

**Comment by ayiaq1** [comment]
props 需要加上disabled

**Comment by qq1390229143** [comment]
propsDisabled: 'disabled',
this.propsDisabled = props.disabled;
这两句看的不矛盾?
不传值就是undefined了

**Comment by qq1390229143** [comment]
if(props.disabled){
this.propsDisabled = props.disabled
}
这样不是更好?

**Comment by ayiaq1** [comment]
下次发包的时候会增加兼容性判断,再此之前可以加props.disabled

**Comment by qq1390229143** [comment]
好的
