### ISSUE TITLE
@click @click.native @focus都无法触发

### ISSUE THREAD

**Issue by 068089dy** [ayiaq1/el-tree-select#53]

**Comment by ayiaq1** [comment]
你想要的结果是什么，通过什么触发？支持render

**Comment by 068089dy** [comment]
> 你想要的结果是什么，通过什么触发？支持render

就是普通的点击,点击控件后执行一个方法,像这样:
```
<el-tree-select
            ...
            @click.native="_clickAddReportType"
          />
```

**Comment by ayiaq1** [comment]
[Demo](https://codepen.io/ayiaq1/pen/rNaEzdz?editors=1011)

[API](https://ayiaq1.github.io/el-tree-select/website/#/components/ElTreeSelect)

甚至可以使用render方式，自定义click

```
 <el-tree-select  v-model="values" :treeRenderFun="_renderFun"  ref="treeSelect"/>

       // 自定义render
        _renderFun(h, { node, data, store }) {
            return (
                <span class='custom-tree-node'>
                    <link on-click={()=>this._nodeClick(node,data)}>{node.label}</link>
                </span>
            );
        }
```

**Comment by 068089dy** [comment]
![image](https://user-images.githubusercontent.com/20868453/85971110-dbe0dc80-b9fe-11ea-861c-6edcd9528af3.png)
我想点的是最上面那个框,不是下面的列表

**Comment by ayiaq1** [comment]
没有相关的API ，但是可以通过 this.$refs.treeSelect._popoverShowFun() 复写  
也可以 this.$refs.treeSelect.$refs.select去处理el-select
为什么要触发这个事件？

**Comment by 068089dy** [comment]
试了下`el-tree`的确不支持click.

我把`ElTreeSelect.vue`506行修改了一下,让focus事件继续传递,就可以捕获事件了.

```js
// 显示弹出框的时候容错，查看是否和el宽度一致
    _popoverShowFun(val) {
      this._updateH()
      this.$emit('focus')
    },
```

**Comment by 068089dy** [comment]
至于为什么要触发这个事件,

产品总会给你想不到的需求.
