### ISSUE TITLE
单选怎么用呢?

### ISSUE THREAD

**Issue by Rubber-duck1988** [ayiaq1/el-tree-select#55]
单选怎么用呢?能不能做成有复选框 然后勾选后其他复选框禁用掉

**Comment by ayiaq1** [comment]
通过v-model类型判断是否多选  
```
 v-model="id"
id:''  单选   id:[] 多选
```

**Comment by Rubber-duck1988** [comment]
你好,单选出来了 但是选择不上 或者数据对不上 请问是还要设置其他参数吗?

**Comment by Rubber-duck1988** [comment]
> 通过v-model类型判断是否多选
> 
> ```
>  v-model="id"
> id:''  单选   id:[] 多选
> ```

你好,单选出来了 但是选择不上 或者数据对不上 请问是还要设置其他参数吗?

**Comment by Rubber-duck1988** [comment]
> > 通过v-model类型判断是否多选
> > ```
> >  v-model="id"
> > id:''  单选   id:[] 多选
> > ```
> 
> 你好,单选出来了 但是选择不上 或者数据对不上 请问是还要设置其他参数吗?

应该说 我想要父子不关联,可以单选一级 或者单选二级,请问这种情况可以实现吗

**Comment by ayiaq1** [comment]
和element-ui一致 使用的就是el-tree api 
```
treeParams  :     支持el-tree 相关参数
check-strictly
```

**Comment by Rubber-duck1988** [comment]
> 和element-ui一致 使用的就是el-tree api
> 
> ```
> treeParams  :     支持el-tree 相关参数
> check-strictly
> ```

感谢~~
我在treeParams对象里面加了checkStrictly: true,  clickParent: true就可以了
