### ISSUE TITLE
9.28该版本有bug

### ISSUE THREAD

**Issue by xiaofute** [ayiaq1/el-tree-select#57]
如题
![image](https://user-images.githubusercontent.com/28945380/94411914-bb662100-01ab-11eb-9e51-5f45359a8faf.png)

**Comment by cdfan** [comment]
对呀，更新后启动的时候报模块找不到，上一个版本就没有问题

**Comment by ayiaq1** [comment]
怎么注入的？ npm安装之后 Vue.use?

**Comment by ayiaq1** [comment]
3.1.10已紧急修复。公司内网禁止了publish dist，不好意思！
