### ISSUE TITLE
当子节点全部选中时，父节点呈现选中状态，但是实际values不包含

### ISSUE THREAD

**Issue by shlroland** [ayiaq1/el-tree-select#59]
我需要只选中末尾的节点，不需要包含父节点。现在的情况是，子节点全部选中后，父节点也被自动选中了，如果开启check-strictly，则父节点无法呈现选中状态

**Comment by ayiaq1** [comment]
这个需求目前element-ui也是这样的。如果要做视觉上的效果，可以将父节点 disabled 设置为true
