### ISSUE TITLE
搜索栏是否可以配置取消？clickParent设为true不能自动关闭下拉框？

### ISSUE THREAD

**Issue by inmWang** [ayiaq1/el-tree-select#6]
搜索栏是否可以配置取消？clickParent设为true不能自动关闭下拉框？

**Comment by ayiaq1** [comment]
搜索栏隐藏可以在下一个版本增加配置，clickParent=true允许点击父级，因此只会抛出nodeClick

**Comment by ayiaq1** [comment]
2.0.6
