### ISSUE TITLE
点击复选框时会选中所有子节点，但是点击文字部分只会选中父节点，这个有办法配置吗？

### ISSUE THREAD

**Issue by 068089dy** [ayiaq1/el-tree-select#65]
我想点击文字部分也选中所有子节点：
![image](https://user-images.githubusercontent.com/20868453/101878637-dfda7280-3bca-11eb-9357-2f52da8d0929.png)

**Comment by ayiaq1** [comment]
leafOnly: true,的情况下 顶级只会有勾选，不会对文本框设值。
可以当做优化，后续增加。

**Comment by ayiaq1** [comment]
3.1.13已更新
npm是最新的，
cnpm收录好像有一个延迟

clickParent=false 可以阻止父级点击冒泡

具体参考 App.vue
