### ISSUE TITLE
BUG 结果框无法和树联动，移除了数据之后树还是选中状态

### ISSUE THREAD

**Issue by zuoliang0** [ayiaq1/el-tree-select#68]
如题

**Comment by zuoliang0** [comment]
当一个父节点下面所有节点都被选中之后，再通过结果框移除树不能取消选中

**Comment by ayiaq1** [comment]
提供下在线demo?我这边测试没问题

**Comment by zuoliang0** [comment]
这个不好提供，因为使用在其他项目中集成的，算了，我再研究一下吧

**Comment by zuoliang0** [comment]
我知道了，是版本太老了，我用你这边比较老的版本导致的。

不过建议更新一下 在线测试 我发现”下拉树参数“更新了data不会生效

**Comment by ayiaq1** [comment]
新版本走更新方法，避免双向绑定导致性能问题
