### ISSUE TITLE
直接在组件内使用时，引入的不是一个正常的ElTreeSelect组件

### ISSUE THREAD

**Issue by jxgahxs** [ayiaq1/el-tree-select#69]
在组件内部单独使用时，通过import ElTreeSelect from 'el-tree-select'  此时导入的虽然是一个对象，并且也具备了install函数。但是其内部对象为install函数与Components数组对象迭代产生的结果。

![image](https://user-images.githubusercontent.com/23493614/123394109-596b0880-d5d1-11eb-936a-0351a4035224.png)

**Comment by ayiaq1** [comment]
没看懂呢，什么问题？源码全局引入之后使用  el-tree-select 报空？
参考一下 main.js
```
import ElTreeSelect from './components/src/ElTreeSelect';

...


Vue.component(ElTreeSelect.name, ElTreeSelect);
```

使用：
```
 treeSelect.vue
```

**Comment by jxgahxs** [comment]
我在组件内部引入,没有在main.js中。看到index.js有export出Components（组件列表）。此时我想应该可以按需引入。

**Comment by ayiaq1** [comment]
如果内部用的话可以只对components的源码放到项目里面。目前打包没有做处理。
或者你工程内安装 babel-plugin-component， 然后参考element-ui官网修改配置。
