### ISSUE TITLE
可否明确一下开源协议配置在 package.json 里? 

### ISSUE THREAD

**Issue by novaeye** [ayiaq1/el-tree-select#73]
如题, 想在传统(前后端不分离)的java工程中通过 [webjars](https://www.webjars.org) 方式使用, 但是 webjars 打包时要求必须有在 package.json 中声明开源协议.

**Comment by ayiaq1** [comment]
直接从 github上拉吧 "license": "BSD"

**Comment by ayiaq1** [comment]
3.1.14 npm 包更新了
